---
title: "Create Floodplain Forest Predictors"
date: "`r Sys.Date()`"
output: html_document
---

# Introduction

[IWR Planning Assistance Library](https://ecolibrary.planusace.us/)

  -  Log in
  -  Search: "UMRS Floodplain Forest Habitat Model"
  -  Download: 
      -  "UMRS Floodplain Forest Model Documentation and Application Guide"
      -  "UMRS Floodplain Forest Model Application Spreadsheet"


```{r echo=FALSE, message=FALSE, warning=FALSE}
library(nybem)
library(readr)
```


# Import Observations
```{r}
forest_observations <- read_csv("input/forest_observations.csv",
                                show_col_types = FALSE)
```


```{r echo=FALSE, eval=FALSE}
library(DataEditR)
# https://cran.r-project.org/web/packages/DataEditR/vignettes/DataEditR.html

data_edit(forest_observations, 
          theme = "sandstone",
          col_edit = FALSE, row_edit = TRUE,
          col_names = FALSE, col_readonly = c("unit"),
          save_as = "input/forest_observations.csv", 
          read_fun = "read_csv", write_fun = "write_csv",
          hide = TRUE)
```
