---
title: "Create Floodplain Forest Model"
date: "`r Sys.Date()`"
output: html_document
---

# Introduction

[IWR Planning Assistance Library](https://ecolibrary.planusace.us/)

  -  Log in
  -  Search: "UMRS Floodplain Forest"
  -  Download: 
      -  "UMRS Floodplain Forest Model Documentation and Application Guide"
      -  "UMRS Floodplain Forest Model Application Spreadsheet"

# Define Habitat Suitability Index Values
```{r echo=FALSE, message=FALSE, warning=FALSE}
library(nybem)
library(readr)
```

```{r echo=FALSE}
#' @title Slope Intercept Function
#'
#' @description A linear function in the slope-intercept form 
#' (y = mx +b). Allows the y term to be calculated when the slope and the 
#' y-intercept terms are known. 
#'
#' @export
#' @param x  numeric; The independent variable x. The value for which the 
#'           corresponding y term will calculated provided the specified 
#'           slope and y-intercept.
#' @param b  numeric; The y-intercept term. 
#' @param m  numeric; The slope term. 
#' 
#' @return The y term of the linear function y = mx + b.
#'
si <- function(x, b, m) {
  y = (m * x) + b
}
```

```{r}
# Define the model using the `ecorest` model format
ff_model <- data.frame(
  canopy_per         = c(0, 20, 40, 70, 80, 90, NA),
  canopy_SIV         = c(si( 0,  0.0,  0.005),
                         si(20, -0.2,  0.015),
                         si(40, -0.4,  0.020),
                         si(70,  1.0,  0.000),
                         si(80,  2.6, -0.020),
                         si(90,  0.8,  0.000),
                         NA),
  type_per           = c(0, 20, 40, 60, 75, 100, NA),
  type_SIV           = c(si(  0,  0.0, 0.0050),
                         si( 20, -0.1, 0.0100),
                         si( 40, -0.3, 0.0150), # corrected slope error
                         si( 60, -0.2, 0.0133),
                         si( 75,  0.2, 0.0080),
                         si(100,  0.0, 0.0100),
                         NA),
  invasive_per       = c(0, 10, 20, 40, 50, 75, 100),
  invasive_SIV       = c(si(  0,  1.0,  -0.01),
                         si( 10,  1.5,  -0.06),
                         si( 20,  0.5,  -0.01),
                         si( 40,  0.3,  -0.005),
                         si( 50,  0.13, -0.0016),
                         si( 75,  0.04, -0.0004),
                         si(100,  0.0,   0.0)),
  stocking_per       = c(0, 20, 40, 80, 100, NA, NA),
  stocking_SIV       = c(si(  0,  0.00,  0.005),
                         si( 20, -0.30,  0.020),
                         si( 40,  0.10,  0.010),
                         si( 80,  0.50,  0.005),
                         si(100,  0.00,  0.010),
                         NA,
                         NA),
  structural_div     = c(0, 1, NA, NA, NA, NA, NA),
  structural_div_SIV = c(si(  0,  0.00,  1.0),
                         si(  1,  0.00,  1.0),
                         NA,
                         NA,
                         NA,
                         NA,
                         NA)
)

# Create model labels
ff_labels <- data.frame(
  model = "Floodplain Forest",
  label = c("Canopy Cover (%)", 
            "Desired Forest type (%)", 
            "Invasive Species (%)", 
            "Desired Stocking Regen (%)",
            "Structural Diversity"),
  variable = c("canopy_per", 
               "type_per", 
               "invasive_per", 
               "stocking_per",
               "structural_div")
)
```

```{r fig.width=6, fig.height=9}
nybem::HSIplotter(ff_model,
                  xlab = ff_labels$label,
                  ylab = ff_labels$variable)
```

# Import Observations
```{r}
forest_observations <- read_csv("input/forest_observations.csv",
                                show_col_types = FALSE)
```

# Calculate Metrics
```{r}

```


- lineupjs
- manipulateWidget
- leaflet.minicharts
- rpivotTable
