---
title: "Pool 12 Forestry HREP: Ecological Modeling"
date: "`r Sys.Date()`"
output: html_document
---

# Introduction

[IWR Planning Assistance Library](https://ecolibrary.planusace.us/)

  -  Log in
  -  Search: "UMRS Floodplain Forest Habitat Model"

# Define Habitat Suitability Index Values
```{r message=FALSE, warning=FALSE}
library(nybem)
```

```{r}
# slope intercept function
iv <- function(x, b, m) {
  return(m * x + b)
}

# Define model thresholds using the formulas in the spreadsheet
canopy_cover_SIV <- c(iv( 0,  0.0,  0.005),
                      iv(20, -0.2,  0.015),
                      iv(40, -0.4,  0.020),
                      iv(70,  1.0,  0.000),
                      iv(80,  2.6, -0.020),
                      iv(90,  0.8,  0.000),
                      NA)
desired_forest_type_SIV <- c(iv(  0,  0.0, 0.0050),
                             iv( 20, -0.1, 0.0100),
                             iv( 40, -0.3, 0.0150),
                             iv( 60, -0.2, 0.0133),
                             iv( 75,  0.2, 0.0080),
                             iv(100,  0.0, 0.0100),
                             NA)
invasive_species_SIV <- c(iv(  0,  1.0,  -0.01),
                          iv( 10,  1.5,  -0.06),
                          iv( 20,  0.5,  -0.01),
                          iv( 40,  0.3,  -0.005),
                          iv( 50,  0.13, -0.0016),
                          iv( 75,  0.04, -0.0004),
                          iv(100,  0.0,   0.0))
desired_stocking_regen_SIV <- c(iv(  0,  0.00,  0.005),
                                iv( 20, -0.30,  0.020),
                                iv( 40,  0.10,  0.010),
                                iv( 80,  0.50,  0.005),
                                iv(100,  0.00,  0.010),
                                NA,
                                NA)
structural_diversity_SIV <- c(iv(  0,  0.00,  1.0),
                              iv(  1,  0.00,  1.0),
                              NA,
                              NA,
                              NA,
                              NA,
                              NA)
```

```{r}
# Define the model using the `ecorest` model format
ff_model <- data.frame(
  canopy_cover_per           = c(0, 20, 40, 70, 80, 90, NA),
  canopy_cover_SIV           = canopy_cover_SIV,
  desired_forest_type_per    = c(0, 20, 40, 60, 75, 100, NA),
  desired_forest_type_SIV    = desired_forest_type_SIV,
  invasive_species_per       = c(0, 10, 20, 40, 50, 75, 100),
  invasive_species_SIV       = invasive_species_SIV,
  desired_stocking_regen_per = c(0, 20, 40, 80, 100, NA, NA),
  desired_stocking_regen_SIV = desired_stocking_regen_SIV,
  structural_diversity       = c(0, 1, NA, NA, NA, NA, NA),
  structural_diversity_SIV   = structural_diversity_SIV
)

# Create model labels
ff_labels <- data.frame(
  model = "Floodplain Forest",
  label = c("Canopy Cover (%)", "Desired Forest type (%)", 
            "Invasive Species (%)", "Desired Stocking Regen (%)",
            "Structural Diversity"),
  variable = c("canopy_cover_per", "desired_forest_type_per", 
               "invasive_species_per", "desired_stocking_regen_per",
               "structural_diversity")
)
```

```{r fig.width=6, fig.height=9}
nybem::HSIplotter(ff_model,
                  xlab = ff_labels$label,
                  ylab = ff_labels$variable)
```


